techblog/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from apps.blog.sitemap import PostSitemap, TagSitemap, BlogSitemap, ChannelSitemap, RootblogSitemap, RootblogPostSitemap
from apps.pages.sitemap import PageSitemap

sitemaps = { 'blogs' : BlogSitemap,
             'channels' : ChannelSitemap,
             'rootblog' : RootblogSitemap,
             'posts' : PostSitemap,
             'rootblogposts' : RootblogPostSitemap,
             'pages' : PageSitemap,
             'tags' : TagSitemap }

urlpatterns = patterns('',

    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),

    #url(r'^$', 'apps.blog.views.blog_front', {"blog_slug":"test-blog"}),
)


urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}) )


def bad(request):
    """ Simulates a server error """
    1/0

urlpatterns += patterns('',

    (r'^bad/$', bad),
    (r'^', include('techblog.apps.blog.urls'), {"blog_slug":settings.DEFAULT_BLOG_SLUG, "blog_root":"/"}),

    (r'^blog/(?P<blog_slug>[\w-]*)/', include('techblog.apps.blog.urls') ),

    (r'^comments/', include('techblog.apps.comments.urls')),
    (r'^accounts/', include('techblog.apps.accounts.urls')),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^', include('techblog.apps.pages.urls')),

)

techblog/apps/pages/models.py
from django.db import models

from techblog import markup
from techblog.markup.fields import MarkupField
from techblog.markup.extendedmarkup import combine_sections
from techblog.markup.render import render

class PageBase(models.Model):

    name = models.CharField("Name", default="", blank=True, max_length=255)
    template = models.CharField("Page template", default="", blank=True, max_length=255)

    def __unicode__(self):
        return self.name

class PublishedPageManager(models.Manager):

    def get_query_set(self):
        return super(PublishedPageManager, self).get_query_set().filter(published=True, version='live')


class Page(models.Model):

    base = models.ForeignKey(PageBase, blank=True, null=True)
    parent = models.ForeignKey("Page", blank=True, null=True)
    path = models.CharField("Page path", max_length=255, blank=True)

    title = models.CharField("Page Title", max_length=100)
    slug = models.SlugField("Slug", max_length=100, db_index=True)

    inherit = models.BooleanField("Inherit parent's content?", default=False)
    created_time = models.DateTimeField(auto_now_add=True)
    edit_time = models.DateTimeField(auto_now=True)
    published = models.BooleanField("Display on site?", default=False)
    promoted = models.BooleanField("Display in children list?", default=True)


    content = MarkupField(default="", blank=True, renderer=render)

    objects = models.Manager()
    published_pages = PublishedPageManager()


    version = models.CharField("Version", max_length=100, default="live")
    version_id = models.IntegerField("Parent Page ID", blank=True, null=True)


    allow_comments = models.BooleanField(default=True)
    show_comments = models.BooleanField(default=True)


    def __unicode__(self):
        if self.version != 'live':
            return "%s (%s)" % (self.path, self.version)
        return self.path

    def get_sections(self):

        visited = set()

        sections_to_combine = []
        page = self
        while page is not None and page.id not in visited:
            visited.add(page.id)
            sections_to_combine.append(page.content_data.get('sections'))
            if not page.inherit:
                break
            page = page.parent

        sections_to_combine = sections_to_combine[::-1]

        if self.base is not None:
            sections_to_combine.append(self.base.content_data.get('sections'))

        sections = combine_sections( *sections_to_combine )

        return sections

    def get_template_names(self):

        templates = ["page/page.html"]
        if self.base and self.base.template:
            templates.insert(0, self.base.template)

        return templates

    @models.permalink
    def get_absolute_url(self):

        return ("page", (self.path,))

    def save(self, *args, **kwargs):
        self.create_path()
        return super(Page, self).save(*args, **kwargs)

    def create_path(self):

        pages_checked = set()
        page = self
        page_components = []

        while page is not None and page.id not in pages_checked:
            page_components.append(page.slug)
            pages_checked.add(page.id)
            page = page.parent

        path = "/".join(page_components[::-1])
        self.path = path


    @classmethod
    def page_from_path(cls, path):

        components = path.split('/')

        page = None
        for component in components:
            try:
                page = Page.objects.get(slug=component, parent=page, published=True, version='live')
            except Page.DoesNotExist:
                return None
        return page

    def get_children(self):

        children = Page.published_pages.all()
        return children

    def get_promoted_children(self):

        children = self.get_children().filter(promoted=True)
        return children



    def get_parent_version(self):

        if self.version_id is None:
            return self
        parent_page = Page.objects.get(self.version_id)
        return parent_page


    def get_version(self, version):

        """ Retrieve a versioned page. """

        if self.version == version:
            return self

        parent_version_id = self.get_parent_version().id

        try:
            versioned_page = Page.objects.get(version_id=parent_version_id, version=version)
            return versioned_page
        except Page.DoesNotExist:
            versioned_page = Page(version_id=parent_version_id, published=False, version=version)
            versioned_page.save()

        copy_attribs = ['parent',
                        'path',
                        'title',
                        'slug',
                        'inherit',
                        'created_time',
                        'edit_time',
                        'promoted']

        for attrib in copy_attribs:
            setattr(versioned_page, attrib, getattr(self, attrib))
        versioned_page.save()

        return versioned_page

    def delete_version(self, version):

        """Removes the draft object associated with a page."""

        parent_version_id = self.get_parent_version().id

        try:
            versioned_page = Page.objects.get(version_id=parent_version_id,
                                              version=version)
            versioned_page.delete()
        except Page.DoesNotExist:
            pass

    def version_exists(self, version):

        parent_version_id = self.get_parent_version().id

        try:
            versioned_page = Page.objects.get(version_id=parent_version_id, version=version)
            return True
        except Page.DoesNotExist:
            return False

techblog/apps/blog/forms.py
from django import forms

class ImportForm(forms.Form):

    blog_slug = forms.CharField("Blog slug")
    input_file = forms.FileField()

    include_tags = forms.CharField("Included tags", required=False)
    exclude_tags = forms.CharField("Excluded tags", required=False)

    format = forms.CharField("Import format", widget=forms.HiddenInput, initial="WXR")

class WriterForm(forms.Form):

    title = forms.CharField(label="Post Title", required=True)
    slug = forms.CharField(label="Post Slug", required=True)
    tags = forms.CharField(label="Tags (comma separated)", required=True)

    post = forms.CharField(label="Post Content", required=False)

techblog/apps/pages/forms.py
from django import forms

class WriterForm(forms.Form):

    title = forms.CharField(label="Post Title", required=True)
    slug = forms.CharField(label="Post Slug", required=True)


    content = forms.CharField(label="Post Content", required=False)

techblog/templates/page/page.html
{% extends "blog/base.html" %}
{% load markuptags %}

{% load comments %}

{% block title %}{{ page.title }}{% endblock %}

{% block summary_area %}
<div class="faded-title"><a href="{{ blog.get_absolute_url }}">{{ page.title }}</a></div>
<h1>{{ blog.tagline }}</h1>
{% if section.intro %}<div class="summary-area">{% markupsection sections "intro" %}</div>{% endif %}
{% endblock %}



{% block column1 %}

{% markupsection sections "main" %}


{% get_comments for page as comments %}

<a name="comments"> </a>
{% if comments and page.show_comments %}
<div class="comments">
    <h2>{{ comments.count }} Comment{{ comments.count|pluralize }} on "{{ page.title }}"</h2>
    {% include "blog/includes/comments.html" %}
</div>
{% endif %}

{% if page.allow_comments %}
{% get_comment_form for page as comment_form %}
{% include "blog/includes/comment_form.html" %}
{% endif %}

{% endblock %}



{% block column2 %}

{% if not is_preview and not user.is_anonymous %}
<div class="module-header">Admin Options</div>
<div class="module">
    <ul class="links-list">
        <li><a href="{% url pagewriter page.id %}">Edit this Page</a></li>
        <li><a href="/admin/pages/page/{{ page.id}}">Admin Page</a></li>
    </ul>

</div>
{% endif %}

{% markupsection sections "column2" %}
{% endblock %}


{% block js_foot %}
<script type="text/javascript" src="/media/js/comments.js"> </script>
{% endblock %}

techblog/templates/page/write.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<style type="text/css">

*{
    padding:0px;
    margin:0px;
}
html,body{
      margin:0;
      padding:0;
      height:100%;
      border:none;
      font-family:arial;
      font-size:12px;
      background-color:#ccc;
   }

#id_title, #id_tags_text, #id_slug
{
 width:99%;
}

label
{
    font-weight:bold;
}

label[for=id_tags_text],label[for=id_title],label[for=id_slug]
{
    float:right;
}

input[type=text], textarea
{
    border:1px solid #0066CC;
    padding:2px;
}

input[type=checkbox]
{
    border:1px solid #0066CC;
    padding:2px;
}

.option
{
    width:200px;
    float:left;
}

.buttons
{
    margin-top:10px;
}

input[type=submit]
{
    margin-right:20px;
    min-width:120px;
}

</style>

</head>
<body>


<div style="height: 90%; padding:10px;">
<form style="height:100%" action="{% url pagewriter edit_page.id %}" method="post">



<div>
    <table width="100%">
        <tr>
            <td width="200px"><label for="id_title">Title</label></td>
            <td><input type="text" id="id_title" name="title" value="{{ page.title }}"></input></td>
        </tr>

        <tr>
            <td width="200px"><label for="id_slug">Slug</label></td>
            <td><input type="text" id="id_slug" name="slug" value="{{ page.slug }}"></input></td>
        </tr>

        <tr>
            <td></td>
            <td>
            <div class="option">
                <input type="checkbox" id="id_inherit" name="inherit" {% if page.inherit %}checked="checked"{% endif %}></input>
                <label for="id_published">Inherit content from parent?</label>
            </div>
            <div class="option">
                <input type="checkbox" id="id_promoted" name="promoted" {% if page.promoted %}checked="checked"{% endif %}></input>
                <label for="id_promoted">Promoted?</label>
            </div>
            <div class="option">
                <input type="checkbox" id="id_published" name="published" {% if page.published %}checked="checked"{% endif %}></input>
                <label for="id_published">Visible on site?</label>
            </div>
            <div class="option">
                <input type="checkbox" id="id_allow_comments" name="allow_comments" {% if page.allow_comments %}checked="checked"{% endif %}></input>
                <label for="id_allow_comments">Allow comments?</label>
            </div>
            </td>
        </tr>
    </table>
</div>

<textarea style="width:99%;height:85%;margin-top:10px;" id="id_content" name="content">{{ page.content }}</textarea>
<div class="buttons">
    <input type="submit" type="button" name="preview" value="Preview"></input>
    <input type="submit" name="save" value="Save"></input>
    <input type="submit" name="revert" value="Revert" onclick="return confirm('Revert to previously published version?')"></input>
    <input type="submit" name="publish" value="Publish" onclick="return confirm('Publish this page?')"></input>
    {# <a href="{% url blog_post blog.slug page.display_time.year page.display_time.month page.display_time.day post_slug %}" target="_blank">View on site</a> #}
    <a href="/admin/resources/imageupload/add/" target="_blank">Upload an image</a>
    <a href="/admin/resources/imageupload/" target="_blank">View Images</a>
</div>

</form>

</div>

{% if auto_url %}
<script>
window.open("{{ auto_url }}", 'previewpage_{{ page.id }}');
</script>
{% endif %}

</body>