techblog/apps/blog/urls.py
import views
from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse
from feeds import BlogFeed, BlogTagFeed

feeds = {
    'posts': BlogFeed,
    'tag' : BlogTagFeed
}


urlpatterns = patterns('',

    url(r'^xhr/preview_comment/$', views.xhr_preview_comment, name="xhr_preview_comment"),

    url(r'^tools/import/$', views.import_wxr, name='import_wxr'),
    url(r'^feeds/(?P<feed_item>.+)/$', views.feeds, {'feed_dict': feeds}, name="blog_feeds"),

    url(r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<slug>[\w-]*)/$', views.blog_post, name="blog_post"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/$', views.blog_month, name="blog_month"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/page/(?P<page_no>\d+)/$', views.blog_month, name="blog_month_with_page"),

    url(r'^tag/(?P<tag_slug>[\w-]*)/$', views.tag, name="blog_tag"),
    url(r'^tag/(?P<tag_slug>[\w-]*)/page/(?P<page_no>\d+)/$', views.tag, name="blog_tag_with_page" ),

    url(r'^page/(?P<page_no>\d+)/$', views.blog_front, name="blog_front_with_page"),
    url(r'^search/$', views.blog_search, name="blog_search"),

    url(r'^writer/(?P<post_id>\d+)/$', views.writer, name="writer"),
    url(r'^newpost/$', views.newpost, name="newpost"),
    url(r'^manage/$', views.manage, name="manage"),

    url(r'^$', views.blog_front, name="blog_front"),

    )

techblog/apps/comments/urls.py
import views
from django.conf.urls.defaults import *

urlpatterns = patterns('',

    url('^xhr/post/$', views.xhr_post_comment, name='xhr_post_comment'),
    url('^xhr/delete/$', views.xhr_delete_comment, name='xhr_delete_comment'),
    url('^success/$', views.post_success, name="post_success"),
                       )

techblog/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from apps.blog.sitemap import PostSitemap, TagSitemap, BlogSitemap, ChannelSitemap, RootblogSitemap, RootblogPostSitemap
from apps.pages.sitemap import PageSitemap

sitemaps = { 'blogs' : BlogSitemap,
             'channels' : ChannelSitemap,
             'rootblog' : RootblogSitemap,
             'posts' : PostSitemap,
             'rootblogposts' : RootblogPostSitemap,
             'pages' : PageSitemap,
             'tags' : TagSitemap }

urlpatterns = patterns('',

    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),

    #url(r'^$', 'apps.blog.views.blog_front', {"blog_slug":"test-blog"}),
)


urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}) )


def bad(request):
    """ Simulates a server error """
    1/0

urlpatterns += patterns('',

    (r'^bad/$', bad),
    (r'^', include('techblog.apps.blog.urls'), {"blog_slug":settings.DEFAULT_BLOG_SLUG, "blog_root":"/"}),

    (r'^blog/(?P<blog_slug>[\w-]*)/', include('techblog.apps.blog.urls') ),

    (r'^comments/', include('techblog.apps.comments.urls')),
    (r'^accounts/', include('techblog.apps.accounts.urls')),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^', include('techblog.apps.pages.urls')),

)

techblog/apps/blog/models.py
from django.db import models

from django.contrib.auth.models import User
from techblog.markup.fields import PickledObjectField
from django.utils.safestring import mark_safe
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

from django.contrib.auth.models import User

from techblog.markup.render import render
from techblog.markup.fields import MarkupField
from techblog import broadcast

import markup
import operator
import datetime
import os
import os.path
from itertools import groupby

from django.contrib.sitemaps import ping_google

@broadcast.recieve
def new_content_on_site():
    ping_google('/sitemap.xml')




#
#from django.db.models.signals import post_save
#
#
#def _process_tags_signal(sender, **kwargs):
#    sender.
#
#post_save.connect(process_tags, sender=Post)

class Author(models.Model):

    user = models.ForeignKey(User)

    bio = MarkupField(default="", blank=True, renderer=render)


class Tag(models.Model):

    blog = models.ForeignKey("Blog")
    name = models.CharField("Tag name", max_length=100)
    slug = models.SlugField(max_length=100, db_index=True)

    template = models.CharField("Template", max_length=100, blank=True)

    count = models.IntegerField(default=0, editable=False)

    description = MarkupField(default="", blank=True, renderer=render)

    def get_summary(self):
        if self.description_summary_html:
            return self.description_summary_html
        else:
            return self.description_html


    def decrement(self):
        count = self.count
        if count:
            count -= 1
            self.count = count
        return count

    def increment(self):
        self.count += 1
        return self.count

    def __unicode__(self):
        return "%s (in %s)" % (self.name, self.blog)

    def posts(self):

        now = datetime.datetime.now()
        posts = self.post_set.filter( published=True,
                                        display_time__lte=now,
                                        version="live",
                                         ).order_by('-display_time')
        return posts

    @models.permalink
    def get_absolute_url(self):
        return ("blog_tag", (),
                dict(blog_slug=self.blog.slug, tag_slug=self.slug))

    def get_blog_relative_url(self):

        return "tag/%s/" % self.slug


    def get_feed(self):
        import feeds
        title = "RSS Feed for %s posts in %s" % (self.name, self.blog.title)
        url = feeds.BlogTagFeed.get_url(self)
        return dict(title=title, url=url)


class ChannelTag(object):

    def __init__(self, channel_slug, tag_slug):
        self.tag_slug = tag_slug
        self.tags = Tag.objects.filter(slug=self.tag_slug)
        self.channel = Channel.objects.get(slug=channel_slug)
        self.description_data = {}
        if not self.tags.count():
            raise Tag.DoesNotExist

    def posts(self):

        query = models.Q()
        for tag in self.tags:
            query = query | models.Q(id__in = tag.post_set.values('pk').query)
        posts = Post.published_posts.filter(query).order_by('-display_time')

        return posts

    def get_feed(self):
        import feeds
        name = Tag.objects.filter(slug=self.tag_slug)[0].name
        title = "RSS Feed for %s posts in %s" % (name, self.channel.title)
        url = feeds.ChannelTagFeed.get_url(self)
        return dict(title=title, url=url)

    def get_absolute_url(self):
        try:
            return reverse("apps.blog.views.tag", kwargs=dict(blog_slug=self.channel.slug, tag_slug=self.tag_slug))
        except Exception, e:
            pass

    def __getattr__(self, attr):
        return getattr(self.tags[0], attr)



class Channel(models.Model):

    template = models.CharField("Template", max_length=100, blank=True)

    title = models.CharField("Channel Title", max_length=100)
    tagline = models.CharField("Tag line", max_length=200)
    slug = models.SlugField(max_length=100, db_index=True)
    posts_per_page = models.IntegerField(default=10)

    template = models.CharField("Template prefix", max_length=100, blank=True)

    description = MarkupField(default="", renderer=render, blank=True)

    blogs = models.ManyToManyField("Blog")

    def is_channel(self):
        """ Returns True if this is a channel (for the benefit of tempalates) """
        return True

    def child_blogs(self):
        return list(self.blogs.order_by('title'))

    def get_full_template_name(self, template_name):
        return self.template.rstrip('/') + '/' + self.template

    def get_template_names(self, template_name):
        template_prefix = self.template.rstrip('/')
        return [template_prefix + '/' + template_name, 'theme/'+template_name, template_name]


    def __unicode__(self):
        return self.title

    def posts(self):
        now = datetime.datetime.now()

        posts = Post.objects.filter( blog__in = self.blogs.all(),
                                     published=True,
                                     version="live",
                                     display_time__lte=now).order_by("-display_time")
        return posts


    def get_tag(self, tag_slug):

        channel_tag = ChannelTag(self.slug, tag_slug)
        return channel_tag


    def tags(self):

        tags = []
        for blog in self.blogs.all():
            tags += list(blog.tags())
        tags.sort(key=lambda t:t.slug)

        collated_tags = []
        for tag_slug, similar_tags in groupby(tags, lambda t:t.slug):
            similar_tags = list(similar_tags)
            channel_tag = ChannelTag(self.slug, tag_slug)

            channel_tag.slug = tag_slug
            channel_tag.name = similar_tags[0].name
            channel_tag.description = similar_tags[0].description
            channel_tag.count = sum(tag.count for tag in similar_tags)

            collated_tags.append(channel_tag)

        collated_tags.sort(key=lambda t:-t.count)

        return collated_tags


    def get_tag_cloud(self, tag_count=30):

        return TagCloud(self, max_tags=tag_count)


    @models.permalink
    def get_absolute_url(self):

        channel_slug = self.slug

        return ("blog_front", (),
                dict(blog_slug=channel_slug))

    def get_feed(self):
        import feeds
        title = "%s RSS Feed"%self.title
        url = feeds.ChannelFeed.get_url(self)
        return dict(title=title, url=url)

    def get_template_names(self, template_name, alternates=None):

        alternates = alternates or []

        alternates = [os.path.join(p, template_name) for p in alternates]

        templates = []
        templates += alternates
        templates.append(os.path.join('blog', template_name))

        return templates


class TagCloud(object):

    def __init__(self, blog, max_tags = 30):

        self.blog = blog

        #self.tags = list( Tag.objects.filter(blog=blog).order_by("-count") )
        self.tags = list(blog.tags())
        if max_tags is not None:
            self.tags = self.tags[:max_tags]

        self.min_font = 12.0
        self.max_font = 20.0

    def set_scale(min_font, max_font):

        self.min_font = min_font
        self.max_font = max_font

    def __iter__(self):

        tag_counts = [tag.count for tag in self.tags]

        sorted_counts = sorted(list(set(tag_counts)))
        # tag_counts = [sorted_counts.index(count) for count in tag_counts]

        places = [sorted_counts.index(tag.count) for tag in self.tags]

        if not places:
            return

        max_count = max(places)
        min_count = min(places)
        count_range = float(max_count - min_count)

        font_size_range = self.max_font - self.min_font

        tag_cloud = []
        for place, tag in zip(places, self.tags):

            tag_scale = (place - min_count) / (count_range or 1.0)
            tag_scale = int(round(tag_scale * 10))

            tag_cloud.append( (tag_scale, tag) )

        #tag_cloud = tag_cloud[::2][::-1] + tag_cloud[1::2]
        #tag_cloud = tag_cloud[::-1]

        for size_tag in tag_cloud:
            yield size_tag


class Blog(models.Model):

    owner = models.ForeignKey(User)

    created_time = models.DateTimeField(auto_now_add=True)

    title = models.CharField("Title of the Blog", max_length=100)
    tagline = models.CharField("Tag line", max_length=200, blank=True)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)
    posts_per_page = models.IntegerField(default=10)

    template = models.CharField("Template path", max_length=100)

    description = MarkupField(default="", renderer=render, blank=True)

    def get_full_template_name(self, template_name):
        return self.template.rstrip('/') + '/' + self.template

    def get_template_names(self, template_name, alternates=None):

        alternates = alternates or []

        alternates = [os.path.join(p, template_name) for p in alternates]

        templates = []
        templates += alternates
        templates.append(os.path.join('blog', template_name))

        return templates


    def __unicode__(self):
        return self.title

    def posts(self):
        now = datetime.datetime.now()
        posts = self.post_set.filter(published=True,
                                     version="live",
                                     display_time__lte=now).order_by("-display_time")
        return posts

    def get_tag(self, tag_slug):
        return Tag.objects.get(blog=self, slug=tag_slug)

    def tags(self):
        return self.tag_set.all().order_by("-count")

    @models.permalink
    def get_absolute_url(self):

        blog_slug = self.slug

        return ("blog_front", (),
                dict(blog_slug=blog_slug))

    def get_tag_cloud(self, tag_count=30):

        return TagCloud(self, max_tags=tag_count)


    def get_feed(self):
        import feeds
        title = "%s RSS Feed"%self.title

techblog/apps/comments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from techblog.markup.fields import MarkupField

from techblog import broadcast



def _comment_renderer(markup, markup_type):

    html, summary_html, text, data = broadcast.call.render_comment(markup, markup_type)
    return html, summary_html, text, data

class CommentManager(models.Manager):

    def filter_for_object(self, object):
        ct = ContentType.objects.get_for_model(object)
        comments = Comment.objects.filter(object_id=object.id, content_type=ct, visible=True, moderated=True)
        return comments

    def filter_for_model(self, model):
        ct = ContentType.objects.get_for_model(model)
        comments = Comment.objects.filter(content_type=ct, visible=True, moderated=True)
        return comments

class Comment(models.Model):

    objects = CommentManager()

    content_type = models.ForeignKey(ContentType, db_index=True)
    object_id = models.PositiveIntegerField(db_index=True)
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    visible = models.BooleanField(default=False)
    moderated = models.BooleanField(default=False)

    created_time = models.DateTimeField(auto_now_add=True)

    type = models.CharField("Type of comment", max_length=100, blank=True)
    owner = models.ForeignKey(User, blank=True, null=True, default=None)
    group = models.CharField("Optional comment group", max_length=100, blank=True, default="")

    name = models.CharField("Author's name", max_length=100)
    email = models.EmailField("Author's email", blank=True)
    url = models.CharField(blank=True, default="", max_length=255)
    content = MarkupField(default="", renderer=_comment_renderer)

    def __unicode__(self):
        return self.name



    def site_link(self):
        object_url = self.object_url() + '#comment' +str(self.id)
        url = '''<a href="%s">comment by %s</a>''' % (object_url, self.name)
        return url
    site_link.allow_tags = True

    def object_url(self):
        return self.content_object.get_absolute_url()

    def comment_object_description(self):
        return unicode(self.content_object)

techblog/apps/blog/forms.py
from django import forms

class ImportForm(forms.Form):

    blog_slug = forms.CharField("Blog slug")
    input_file = forms.FileField()

    include_tags = forms.CharField("Included tags", required=False)
    exclude_tags = forms.CharField("Excluded tags", required=False)

    format = forms.CharField("Import format", widget=forms.HiddenInput, initial="WXR")

class WriterForm(forms.Form):

    title = forms.CharField(label="Post Title", required=True)
    slug = forms.CharField(label="Post Slug", required=True)
    tags = forms.CharField(label="Tags (comma separated)", required=True)

    post = forms.CharField(label="Post Content", required=False)

techblog/apps/comments/forms.py
from django import forms


class CommentForm(forms.Form):

    name = forms.CharField(label="Name (required)", required=True)
    email = forms.EmailField(label="Email (not published)", required=False)
    url = forms.CharField(label="Website", required=False)
    content = forms.CharField(label="Comment", widget=forms.Textarea(), required=True)

    content_format = forms.CharField(widget=forms.HiddenInput(), required=True, initial="bbcode")

    content_type = forms.CharField(widget=forms.HiddenInput(), required=True)
    object_id = forms.IntegerField(widget=forms.HiddenInput(), required=True)

    success_url = forms.CharField(widget=forms.HiddenInput())

techblog/templates/blog/includes/archives.html
{% load blogtags %}
{% load humanize %}
{% load markuptags %}
{% load cache %}

{% cache 3600 archive_year archive_month blog.slug %}
{% get_archives for blog as archives %}

<div>
<div class="archives archives-full">
    {% for year,months in archives %}
    <div id="archive-year-{{ year }}">
        <div class="archive-year">
            {{ year }}
        </div>
        <ul class="archive-months">
            {% for month_url, year, month, count in months %}
            <li{% ifequal month archive_month %}{% ifequal year archive_year %} class="current-month"{% endifequal %}{% endifequal %}>
                <div class="archive-month">
                    <a href="{{ month_url }}" title="{{ count }} posts">{{ month|longmonth }}</a>
                </div>
                <div class="archive-count">{{ count }} post{{ count|pluralize }}</div>
            </li>
            {% endfor %}
        </ul>
        <div class="clear">&nbsp;</div>
    </div>
    {% endfor %}
</div>
</div>
{% endcache %}

techblog/templates/blog/includes/comment_form.html
{% load comments %}
{% load markuptags %}

<a name="comment-form"></a>
<div class="blog-comment-form">
<h3>Leave a Comment</h3>

<form id="comment-form" action="post" target="">

        <p>
            <label for="id_name"><strong>Name</strong> (required):</label> <input type="text" id="id_name" name="name"/>
            <div class="comment-form-errors" id="id_name_errors"></div>
        </p>

        <p>
            <label for="id_email"><strong>Email</strong> (not published):</label> <input type="text" id="id_email" name="email"/>
            <div class="comment-form-errors" id="id_email_errors"></div>
        </p>

        <p>
            <label for="id_url"><strong>Website</strong>:</label> <input type="text" id="id_url" name="url"/>
            <div class="comment-form-errors" id="id_url_errors"></div>
        </p>

        <p>
            <label for="id_content"><strong>Comment</strong>:</label> <textarea name="content" cols="40" rows="10" id="id_content" ></textarea>
            <div class="comment-form-errors" id="id_content_errors"></div>
        </p>

{% for field in comment_form %}
{% if field.is_hidden %}{{ field }}{% endif %}
{% endfor %}
<input type="hidden" id="id_success_url" name="success_url" value="{{ request.path }}"></input>

    <div class="comment-form-help">
        You can use <a href="http://en.wikipedia.org/wiki/Bbcode" target="_blank">bbcode</a> in the comment: e.g.
        [b]This is bold[/b], [url]http://www.willmcgugan.com[/url], [code python]import this[/code]
    </div>

    <div class="comment-form-options">
        <a id="comment-preview" href="#" title="Click before posting comment">Preview</a>
        <input id="comment-submit" type="submit" value="Post Comment"></input>
        <span id="comment-submit-working">Posting... </span>
    </div>
</form>
</div>

<div id="comment-preview-working">
    <div class="content">Previewing comment, please wait a moment...</div>
    <img src="/media/images/throbber.gif" />
</div>
<div id="comment-preview-content">
</div>

techblog/templates/blog/includes/comments.html
{% load comments %}
{% if comments %}

<ul class="comments-list">
{% for comment in comments %}
    <li id="comment{{ comment.id }}" class="comment {% cycle '' 'odd' %}">
        <a name="comment{{ comment.id }}"></a>
        <a href="#comment{{ comment.id }}">{% gravatar comment.email 40 "identicon" %}</a>
        <div class="comment-header">
            {% if not user.is_anonymous %}
                <a href="/admin/comments/comment/{{ comment.id }}/">Admin comment</a>
                <a href="#" class="delete-comment-link" onclick="delete_comment({{ comment.id }}, '{{ request.path }}'); return false;">Delete</a>
            {% endif %}
            <div class="comment-author">
                <cite>{% if comment.url %}<a href="{{ comment.url }}" rel="nofollow">{% endif %}{{ comment.name|safe }}</cite>{% if comment.url %}</a>{% endif %}
                {% if not user.is_anonymous %}{% if comment.email %}(<a href="mailto:{{ comment.email }}">{{ comment.email }}</a>){% endif %}{% endif %}
            </div>
            <div class="comment-time">
                {{ comment.created_time|date:"F jS, Y" }}, {{ comment.created_time|date:"P" }}
            </div>
        </div>
        <div class="comment-body">
            {{ comment.content_html|safe }}
        </div>

    </li>
{% endfor %}
</ul>


{% endif %}

techblog/templates/blog/includes/entryadmin.html
{% if not is_preview and not user.is_anonymous %}
<div class="module-header">Admin Options</div>
<div class="module">
    <ul class="links-list">
        <li><a href="/manage/">Manage blog</a></li>
        <li><a href="{% url writer blog.slug post.id %}">Edit this post</a></li>
        <li><a href="/admin/blog/post/{{ post.id}}/">Admin post</a></li>
        <li><a href="?clearcache">Clear cached page</a></li>
        <li><a href="/accounts/logout/?next={{ request.path }}">Logout</a></li>
    </ul>

</div>
{% endif %}

techblog/templates/blog/includes/indexadmin.html
{% if not is_preview and not user.is_anonymous %}
<div class="module-header">Admin Options</div>
<div class="module">
    <ul class="links-list">

        {% if not blog.is_channel %}
        <li><a href="{% url newpost blog.slug %}">New Post</a></li>
        {% else %}
        {% for child_blog in blog.child_blogs %}
        <li><a href="{{ child_blog.get_absolute_url }}"><strong>Blog:</strong> {{ child_blog.title }}</a></li>
        {% endfor %}
        {% endif %}

        <li><a href="/accounts/logout/?next={{ request.path }}">Logout</a></li>
        <li><a href="{% url manage %}">Manage</a></li>
    </ul>

</div>
{% endif %}

techblog/templates/blog/includes/nav.html
{% load blogtags %}
{% if prev_post or next_post %}
<div class="post-navigation">
    {% if prev_post %}
    <div class="prev-post">
        <a href="{% get_post_url blog_root prev_post %}" title="{{ prev_post.title }}">&larr;&nbsp;{{ prev_post.title|truncatewords:6 }}</a>
    </div>
    {% endif %}

    {% if next_post %}
    <div class="next-post">
        <a href="{% get_post_url blog_root next_post %}" title="{{ next_post.title }}">{{ next_post.title|truncatewords:6 }}&nbsp;&rarr;</a>
    </div>
    {% endif %}

    <div class="clear">&nbsp;</div>
</div>
{% endif %}

techblog/templates/blog/includes/post_list.html
{% load blogtags %}
{% load humanize %}
{% load comments %}

{% for post in posts %}

<div class="post separator">

{% render_post_brief post %}

</div>
{% endfor %}

techblog/templates/blog/includes/post_list_brief.html
{% load blogtags %}
{% load humanize %}
{% load comments %}

<div class="search_results">
{% for post in posts %}

<div class="search-result">
<h2><a href="{% get_post_url blog_root post %}">{{ post.title }}</a></h2>

{# <div class="post-subtitle">{{ post.display_time|date:"F jS, Y" }}</div> #}


<p>{{ post.content_text|textilize|truncatewords:"24"|safe }}</p>
</div>

{% endfor %}
</div>